# Generated by Django 4.1 on 2022-08-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem", old_name="Order", new_name="order",
        ),
    ]
