# Generated by Django 4.1 on 2022-08-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_cart_id"),
    ]

    operations = [
        migrations.RenameModel(old_name="Cart_Item", new_name="CartItem",),
    ]
