# Generated by Django 4.1 on 2022-08-31 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_rename_cart_item_cartitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection", options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="customer", options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AlterModelOptions(name="product", options={"ordering": ["title"]},),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="product", name="description", field=models.TextField(null=True),
        ),
    ]
